### ISSUE TITLE
Workflow doesn't work

### ISSUE THREAD

**Issue by devert** [deanishe/alfred-packal-search#4]
I'm on OSX (Sierra) 10.12.6 and having trouble getting this workflow to work anymore.

When I fun `packal workflow {term}` it briefly says it is "Updating packages" but never seems to succeed in updating the workflow cache no matter how long I wait. I see this messaging in debug logs

```
[2018-02-27 22:08:13][STDERR: input.scriptfilter] 22:08:12 workflow.py:2247 DEBUG    workflow version: 1.4.1
22:08:12 packal.py:155 DEBUG    0 workflows in cache
22:08:12 packal.py:374 DEBUG    Updating workflow lists...
22:08:12 packal.py:379 DEBUG    update command : [u'/usr/bin/python', u'/Users/dennisevert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ACEF2C9B-CDF3-4D92-AD58-CE51B0D280A8/update_workflows.py']
22:08:12 background.py:188 DEBUG    [update] command cached: /Users/dennisevert/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-packal-search/update.argcache
22:08:12 background.py:192 DEBUG    [update] passing job to background runner: [u'/usr/bin/python', '/Users/dennisevert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ACEF2C9B-CDF3-4D92-AD58-CE51B0D280A8/workflow/background.pyc', u'update']
22:08:13 workflow.py:2247 DEBUG    workflow version: 1.4.1
22:08:13 background.py:197 DEBUG    [update] background job started
22:08:13 workflow.py:1657 DEBUG    reading settings from /Users/dennisevert/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-packal-search/settings.json
22:08:13 workflow.py:2439 DEBUG    set last run version: 1.4.1
22:08:13 workflow.py:2288 DEBUG    workflow finished in 0.076 seconds
```

If I run `packal update` I get the following in debug logs
```
[2018-02-27 22:10:34][ERROR: action.script] 22:10:34 workflow.py:2247 DEBUG    workflow version: 1.4.1
22:10:34 packal.py:155 DEBUG    0 workflows in cache
22:10:34 packal.py:374 DEBUG    Updating workflow lists...
22:10:34 packal.py:379 DEBUG    update command : [u'/usr/bin/python', u'/Users/dennisevert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ACEF2C9B-CDF3-4D92-AD58-CE51B0D280A8/update_workflows.py']
22:10:34 background.py:188 DEBUG    [update] command cached: /Users/dennisevert/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-packal-search/update.argcache
22:10:34 background.py:192 DEBUG    [update] passing job to background runner: [u'/usr/bin/python', '/Users/dennisevert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.ACEF2C9B-CDF3-4D92-AD58-CE51B0D280A8/workflow/background.pyc', u'update']
22:10:34 workflow.py:2247 DEBUG    workflow version: 1.4.1
22:10:34 background.py:197 DEBUG    [update] background job started
22:10:34 workflow.py:1657 DEBUG    reading settings from /Users/dennisevert/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred-packal-search/settings.json
22:10:34 workflow.py:2439 DEBUG    set last run version: 1.4.1
22:10:34 workflow.py:2288 DEBUG    workflow finished in 0.085 seconds
```

No matter what I try, the workflow cache is always 0.

**Comment by deanishe** [comment]
Sorry, this one slipped through the cracks. I can't tell you what's wrong because the error is in the log file, not the debugger. Use `packal workflows workflow:openlog` to open the log file and post the error.

If it's something simple, I'll fix it, but this workflow is more or less dead because Packal is now an unmaintained zombie.

**Comment by kenneth-hao** [comment]
I met the same problem, @devert . 
See the log means `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position. `.

I reinstalled it. 
It's done.

**Comment by iT-Boyer** [comment]
`packal workflows workflow:openlog`

```sh 
10:00:32 workflow.py:2439 DEBUG    set last run version: 1.4.1
10:00:32 workflow.py:2288 DEBUG    workflow finished in 0.199 seconds
10:06:16 background.py:242 ERROR    [update] command failed with status 1
10:06:42 background.py:242 ERROR    [update] command failed with status 1
12:11:32 background.py:242 ERROR    [update] command failed with status 1
12:12:12 background.py:242 ERROR    [update] command failed with status 1

12:14:03 workflow.py:2265 ERROR    Command '['plutil', '-convert', 'xml1', '-o', '-', u'/Users/jhmac/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/workflow/workflow.py", line 2258, in run
    func(self)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 209, in main
    wf.cached_data('workflows', get_workflows,  max_age=max_age)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 174, in get_workflows
    local_workflows = get_installed_workflows()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 105, in get_installed_workflows
    workflow_dir = get_workflow_directory()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 68, in get_workflow_directory
    prefs = read_plist(ALFRED_PREFS)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 62, in read_plist
    xml = subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['plutil', '-convert', 'xml1', '-o', '-', u'/Users/jhmac/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist']' returned non-zero exit status 1
12:14:03 background.py:242 ERROR    [update] command failed with status 1
12:14:07 workflow.py:2265 ERROR    Command '['plutil', '-convert', 'xml1', '-o', '-', u'/Users/jhmac/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/workflow/workflow.py", line 2258, in run
    func(self)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 209, in main
    wf.cached_data('workflows', get_workflows,  max_age=max_age)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/workflow/workflow.py", line 1890, in cached_data
    data = data_func()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 174, in get_workflows
    local_workflows = get_installed_workflows()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 105, in get_installed_workflows
    workflow_dir = get_workflow_directory()
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 68, in get_workflow_directory
    prefs = read_plist(ALFRED_PREFS)
  File "/Users/jhmac/hsg/hugo/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9E2B4EF5-3926-4D53-97E0-E4758628210D/update_workflows.py", line 62, in read_plist
    xml = subprocess.check_output(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['plutil', '-convert', 'xml1', '-o', '-', u'/Users/jhmac/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist']' returned non-zero exit status 1
12:14:07 background.py:242 ERROR    [update] command failed with status 1

```
